Repository FE-STUDY-2024/COTE, pull requests merged in 2024-04, with the labels that each got.

#1 1주차
  주하/레벨1/K번째수.js
  주하/레벨1/두 개 뽑아서 더하기.js
  주하/레벨1/푸드 파이트 대회.js
  주하/레벨2/JadenCase 문자열 만들기.js
  주하/레벨2/최댓값과 최솟값.js
Labels: 주하

#5 1주차
  나영/레벨1/K번째수.js
  나영/레벨1/두개뽑아서더하기.js
  나영/레벨1/푸드파이트대회.js
  나영/레벨2/JadenCase문자열만들기.js
  나영/레벨2/최댓값과최솟값.js
Labels: 나영

#3 1주차
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  은지/레벨1/K번째수.js
  은지/레벨1/두 개 뽑아서 더하기.js
  은지/레벨1/푸드 파이트 대회.js
  은지/레벨2/JadenCase 문자열 만들기.js
  은지/레벨2/최댓값과 최솟값.js
Labels: 은지

#4 1주차
  민규/레벨1/k번째수.js
  민규/레벨1/두 개 뽑아서 더하기.js
  민규/레벨1/푸드파이트 대회.js
  민규/레벨2/JadenCase 문자열 만들기.js
  민규/레벨2/최댓값과 최솟값.js
Labels: 민규

#8 2주차
  주하/레벨1/2016년.js
  주하/레벨1/[1차] 비밀지도.js
  주하/레벨1/명예의 전당 (1).js
  주하/레벨1/문자열 내 마음대로 정리하기.js
  주하/레벨1/추억 점수.js
  주하/레벨1/카드 뭉치.js
  주하/레벨1/콜라 문제.js
  주하/레벨2/숫자의 표현.js
  주하/레벨2/올바른 괄호.js
  주하/레벨2/이진 변환 반복하기.js
  주하/레벨2/최솟값 만들기.js
Labels: 주하

#11 2주차
  나영/레벨1/[1차] 비밀지도.js
  나영/레벨1/명예의 전당(1).js
  나영/레벨1/문자열 내 마음대로 정렬하기.js
  나영/레벨1/콜라 문제.js
  나영/레벨2/올바른 괄호.js
  나영/레벨2/최솟값 만들기.js
Labels: 나영

#12 2주차
  가현/레벨1/[1차] 비밀지도.js
  가현/레벨1/문자열 내 마음대로 정렬하기.js
  가현/레벨1/콜라 문제.js
  가현/레벨2/올바른 괄호.js
  가현/레벨2/최솟값 만들기.js
Labels: 가현
