Repository FE-STUDY-2024/COTE, pull requests merged in 2024-05, with the labels that each got.

#9 2주차, 3주차
  민규/레벨1/2016년.js
  민규/레벨1/[1차] 비밀지도.js
  민규/레벨1/k번째수.js
  민규/레벨1/두 개 뽑아서 더하기.js
  민규/레벨1/명예의 전당(1).js
  민규/레벨1/문자열 내 마음대로 정렬하기.js
  민규/레벨1/추억 점수.js
  민규/레벨1/카드뭉치.js
  민규/레벨1/콜라 문제.js
  민규/레벨1/푸드파이트 대회.js
  민규/레벨2/JadenCase 문자열 만들기.js
  민규/레벨2/숫자의 표현.js
  민규/레벨2/올바른 괄호.js
  민규/레벨2/이진변환반복하기.js
  민규/레벨2/최댓값과 최솟값.js
  민규/레벨2/최솟값 만들기.js
Labels: 민규

#15 3주차
  나영/레벨1/2016년.js
  나영/레벨1/추억 점수.js
  나영/레벨1/카드 뭉치.js
  나영/레벨2/숫자의 표현.js
  나영/레벨2/이진 변환 반복하기.js
Labels: 나영

#16 3주차
  .prettierrc
  가현/레벨1/2016년.js
  가현/레벨1/K번째수.js
  가현/레벨1/[1차] 비밀지도.js
  가현/레벨1/두 개 뽑아서 더하기.js
  가현/레벨1/문자열 내 마음대로 정렬하기.js
  가현/레벨1/추억 점수.js
  가현/레벨1/카드 뭉치.js
  가현/레벨1/콜라 문제.js
  가현/레벨1/푸드 파이트 대회.js
  가현/레벨2/JadenCase 문자열 만들기.js
  가현/레벨2/숫자의 표현.js
  가현/레벨2/올바른 괄호.js
  가현/레벨2/이진 변환 반복하기.js
  가현/레벨2/최댓값과 최솟값.js
  가현/레벨2/최솟값 만들기.js
Labels: 가현

#14 3주차
  주하/레벨1/2016년.js
  주하/레벨1/추억 점수.js
  주하/레벨1/카드 뭉치.js
  주하/레벨2/숫자의 표현.js
  주하/레벨2/이진 변환 반복하기.js
Labels: 주하

#10 2주차, 3주차
  은지/레벨1/2016년.js
  은지/레벨1/명예의 전당.js
  은지/레벨1/문자열 내 마음대로 정렬하기.js
  은지/레벨1/비밀지도.js
  은지/레벨1/추억 점수.js
  은지/레벨1/카드 뭉치.js
  은지/레벨1/콜라문제.js
  은지/레벨1/폰켓몬.js
  은지/레벨2/숫자의 표현.js
  은지/레벨2/올바른 괄호.js
  은지/레벨2/이진 변환 반복하기.js
  은지/레벨2/최솟값 만들기.js
Labels: 은지
